version: '3.3'
# docker-compose --compatibility up
services:
    es_container:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: es_container
        deploy:
            resources:
                limits:
                    cpus: '8.000'
                    memory: 10G
        restart: always
        logging:
              driver: "json-file"
              options:
                  max-size: "1g"
        environment:
            - TZ=Asia/Taipei
            - node.name=es01
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms8g -Xmx8g
            - discovery.type=single-node
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ./es/data/:/usr/share/elasticsearch/data
        ports:
            - 9200:9200